In [21]:
%load_ext autoreload
%autoreload 2
from pathlib import Path
from src.datasets import LLFFDataset, LLFFDataloader
from src.utils import namedtuple_map
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
data_dir = Path("../mip-nerf-datasets/llff/orchids/")
image_dir = Path("../mip-nerf-datasets/llff/orchids/images/")

In [3]:
# Config.dataset_loader = 'llff'
# Config.white_bkgd = False
# Config.randomized = True
# Config.near = 0.
# Config.far = 1.
# Config.factor = 4
# Config.llffhold = 8
# MipNerfModel.use_viewdirs = True
# MipNerfModel.ray_shape = 'cylinder'
# MipNerfModel.density_noise = 1.



# dataset = LLFFDataset(
#     data_dir=data_dir, split="train",
#     near=0., far=1., to_render_path=False,
#     batching_mode="all_images",
#     factor=1, to_spherify=False, llffhold=8
# )
dataloader = LLFFDataloader(
    data_dir=data_dir, split="train",
    near=0., far=1., to_render_path=False,
    batching_mode="all_images",
    factor=1, to_spherify=False, llffhold=8,
    shuffle=False
)

../mip-nerf-datasets/llff/orchids/images/IMG_4467.JPG
../mip-nerf-datasets/llff/orchids/images/IMG_4468.JPG
../mip-nerf-datasets/llff/orchids/images/IMG_4469.JPG
../mip-nerf-datasets/llff/orchids/images/IMG_4470.JPG
../mip-nerf-datasets/llff/orchids/images/IMG_4471.JPG
../mip-nerf-datasets/llff/orchids/images/IMG_4472.JPG
../mip-nerf-datasets/llff/orchids/images/IMG_4473.JPG
../mip-nerf-datasets/llff/orchids/images/IMG_4474.JPG
../mip-nerf-datasets/llff/orchids/images/IMG_4475.JPG
../mip-nerf-datasets/llff/orchids/images/IMG_4476.JPG
../mip-nerf-datasets/llff/orchids/images/IMG_4477.JPG
../mip-nerf-datasets/llff/orchids/images/IMG_4478.JPG
../mip-nerf-datasets/llff/orchids/images/IMG_4479.JPG
../mip-nerf-datasets/llff/orchids/images/IMG_4480.JPG
../mip-nerf-datasets/llff/orchids/images/IMG_4481.JPG
../mip-nerf-datasets/llff/orchids/images/IMG_4482.JPG
../mip-nerf-datasets/llff/orchids/images/IMG_4483.JPG
../mip-nerf-datasets/llff/orchids/images/IMG_4484.JPG
../mip-nerf-datasets/llff/or

In [4]:
train_loader = iter(dataloader.loader)

In [5]:
batch_data = next(train_loader)

In [6]:
batch_pixels = batch_data["pixels"]

In [7]:
batch_rays = batch_data["rays"]

In [8]:
batch_pixels

tensor([[0.2588, 0.3059, 0.1098],
        [0.3020, 0.3569, 0.1569],
        [0.3216, 0.3765, 0.1843],
        [0.2235, 0.2863, 0.0941],
        [0.2510, 0.3216, 0.1333],
        [0.2000, 0.2667, 0.0902],
        [0.2784, 0.3529, 0.1765],
        [0.2431, 0.3137, 0.1569]])

In [12]:
batch_indices = list(range(8))

In [13]:
raw_rays = namedtuple_map(lambda r: r[batch_indices], dataloader.dataset.rays)

In [16]:
raw_rays.origins[0]

array([-1.155868 ,  1.4018744, -1.       ], dtype=float32)

In [22]:
np.isclose(batch_rays.origins[0], raw_rays.origins[0])

array([ True,  True,  True])

In [23]:
raw_pixels = dataloader.dataset.images[batch_indices]